config/routes.rb
Ink::Application.routes.draw do
  resources :google, only: [:create, :destroy]
  resources :users, :only => [:create, :new, :edit, :show, :update, :destroy]
  resources :trees, :only => [:index, :show, :create, :new] do
    resources :sketches, :only => [:create, :new, :show] do
      resources :votes, :only => [:create]
    end
  end

post '/sketches/random' => 'sketches#random'

  get "google/create"
  get "google/destroy"
  get 'auth/:provider/callback', to: 'google#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'google#destroy', as: 'signout'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/logout' => 'sessions#logout'

  root 'trees#index'

end

app/models/googleuser.rb
class Googleuser < ActiveRecord::Base
  belongs_to :user

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/sketch.rb
class Sketch < ActiveRecord::Base
  belongs_to :user
  belongs_to :tree, counter_cache: true
  belongs_to :parent, class_name: 'Sketch'
  has_many :children, class_name: 'Sketch', foreign_key: 'parent_id'

  def self.random
    self.all.sample
  end

  def self.latest(num)
    self.all.last(num).reverse
  end

  def as_tree
    node_hash = {}
    node_hash[:id] = self.id
    node_hash[:children] = self.children.map(&:as_tree) unless self.children.empty?
    return node_hash
  end
end

app/models/tree.rb
class Tree < ActiveRecord::Base
  has_many :sketches

  def self.by_sketch_count(limit)
    self.order(sketches_count: :desc, created_at: :asc).limit(limit)
  end

  def random_sketch
    if self.sketches.count < 5
      self.sketches.last
    else
      self.sketches.last(5).sample
    end
  end

  def last_sketch
    self.sketches.last.json_data
  end

  def all_sketches_json
    self.sketches.map do |sketch|
      {sketch.id => sketch.json_data}
    end.to_json
  end

  def all_sketches_lineage
    self.sketches.map do |sketch|
      {id: sketch.lineage}
    end.to_json
  end

  def build_tree()
    Sketch.find(self.origin_id).as_tree.to_json
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :sketches
  has_many :votes
  has_one :googleuser

  validates :password, :presence => true, :length => { :minimum => 6 }
  validates :email, :uniqueness => true, :presence => true, :format => /.+@.+\..+/
  validates :username, :first_name, :last_name, :presence => true
  validates :username, :uniqueness => true

  def create_by_google_user(google_user)
    user = User.new
    user.username = google_user.name
    user.password = rand(36**12).to_s(36)
    # rather not need to validate false
    user.save(:validate => false)
    google_user.update(user_id: user.id)

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    current_user != nil
  end

end

app/controllers/google_controller.rb
class GoogleController < ApplicationController
  def new
    @googleuser = Googleuser.new
  end

  def create
    @google_user = Googleuser.from_omniauth(env["omniauth.auth"])
    user = @google_user.user || User.create_by_google_user(@google_user)

    session[:current_user_id] = user.id
    redirect_to root_path
  end

  def destroy
    # not used anymore, right?
    session[:current_google_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:current_user_id] = @user.id
      if session[:new_user_sketch_id]
        sketch = Sketch.find(session[:new_user_sketch_id]).update(user_id: current_user.id)
        session[:new_user_sketch_id] = nil
      end
      redirect_to root_path
    else
      redirect_to :back, flash: {error: "Invalid email/password combination"}
    end
  end

  def logout
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController

  def new
    @tree = Tree.find(params[:tree_id])
  end

  def create
    @tree = Tree.find(params[:tree_id])
    sketch = Sketch.create(tree_id: @tree.id, parent_id: params[:parent_id], json_data: params[:sketch_json])

    if current_user
      sketch.update(user_id: current_user.id)
      correct_redirect = tree_sketch_path(@tree, sketch)
    else
      sketch.update(user_id: 1)
      correct_redirect = login_path
      session[:new_user_sketch_id] = sketch.id
    end

    if sketch.parent.lineage == nil
      sketch.lineage = sketch.id.to_s
    else
      sketch.lineage = sketch.parent.lineage.to_s + "," + sketch.id.to_s
    end
    sketch.save
    respond_to do |format|
      format.json { render :json => {path: correct_redirect } }
    end
  end

  def show
    @tree = Tree.find(params[:tree_id])
    @sketch = Sketch.find(params[:id])
  end

  def random
    sketch = Sketch.random
    tree = sketch.tree
    respond_to do |format|
      format.json { render :json => {path: tree_sketch_path(tree, sketch) } }
    end
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  def index
    @popular_trees = Tree.by_sketch_count(8)
    @latest_sketches = Sketch.latest(25)
  end

  def new
  end

  def create
    tree = Tree.create()
    if current_user
      sketch = Sketch.create(tree_id: tree.id, json_data: params[:sketch_json], user_id: current_user.id)
      tree.update(origin_id: sketch.id)

      respond_to do |format|
        format.json { render :json => {path: tree_sketch_path(tree, sketch)} }
      end
    else
      sketch = Sketch.create(tree_id: tree.id, json_data: params[:sketch_json], user_id: 1)
      tree.update(origin_id: sketch.id)
      session[:new_user_sketch_id] = sketch.id
      respond_to do |format|
        format.json { render :json => {path: login_path} }
      end
    end
  end

  def show
    @tree = Tree.find(params[:id])
    @origin = @tree.origin_id
    @sketches = @tree.sketches
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user].permit(:username, :password, :password_confirmation, :email, :first_name, :last_name))
    if @user.save
      session[:current_user_id] = @user.id
      if session[:new_user_sketch_id]
        sketch = Sketch.find(session[:new_user_sketch_id]).update(user_id: current_user.id)
        session[:new_user_sketch_id] = nil
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @sketches = @user.sketches
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/google_helper.rb
module GoogleHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <p><a href= 'https://github.com/jsum528/ink'>About</a> Eversketch ||  Made with love at <a href="http://devbootcamp.com/2013/04/03/check-out-dbc-chicago-on-built-in-chicago/">DBC Chicago</a></p>
</div>

app/views/layouts/_navbar.html.erb
<nav >
  <ul>
    <li class="nav-ink nav-block"><%= link_to 'Eversketch', root_path, :id => 'logo' %></li>

    <% if session[:current_user_id] %>
    <div class="nav-buttons">
      <% if current_user.first_name != nil%>
      <button class="nav-profile nav-block"><%= link_to current_user.first_name.capitalize + " " + current_user.last_name.capitalize + "'s Sketches", user_path(session[:current_user_id]) %></button>
      <%else%>
      <button class="nav-profile nav-block"><%= link_to current_user.username + "'s Sketches", user_path(session[:current_user_id]) %></button>
      <%end%>
      <button class="nav-create nav-block"><%= link_to 'Create New Sketch', new_tree_path %></button>
      <button class="nav-random nav-block" id="nav-random-button"><a>Random Sketch</a></button>
      <button class="nav-signout nav-block"><%= link_to 'Sign Out', logout_path %></button>

    <%else%>

      <button class="nav-signup nav-block"><%= link_to 'Sign Up', new_user_path %></button>
      <button class="google-signin nav-block"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></button>
      <button class="nav-login nav-block"><%= link_to 'Sign In', login_path, :id => 'login' %></button>
    <%end%>
  </div>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eversketch</title>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <link rel="stylesheet" href="/cristin.css">
  <%= javascript_include_tag "application" %>

  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <%= csrf_meta_tags %>
</head>
<body>


  <%= render '/layouts/navbar' %>

  <div class="page">
    <%= yield %>
  </div>

  <%= render '/layouts/footer' %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li><br>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_new_canvas.html.erb
<div class="new-sketch-container">
<% if params[:parent_id] %>

<div class='lineage-pictures'>
  <h3>Lineage</h3>
  <% parent = Sketch.find(params[:parent_id]) %>
  <% if parent.parent %>
    <% grandparent = parent.parent %>
    <% lineage = [grandparent, parent] %>
    <% if grandparent.parent %>
      <% lineage = [grandparent.parent, grandparent, parent] %>
    <% end %>
  <% else %>
    <% lineage = [parent] %>
  <% end %>
  <% lineage.each_with_index do |lineage_pic, index| %>
    <a href="<%= tree_sketch_path(lineage_pic.tree_id, lineage_pic.id) %>">
      <p><canvas width="600" height="600" class="lineage_pic" id="sketch-<%= index %>"></canvas></p>
    </a>

    <script type="text/javascript">
      var jsonString = '<%= raw lineage_pic.json_data %>';
      var sketchId = "sketch-" + "<%= index %>";
      sketchCanvas = new fabric.StaticCanvas(sketchId, {isDrawingMode: false});
      sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
      $('.lineage_pic').css({'height': '150px', 'width': '150px', 'border': '1px solid black'})
    </script>
    <% if lineage_pic != lineage.last %><p class='arrow'>&#9660;</p><% end %>
  <% end %>
</div>
<% end %>

<div class="format-canvas-elements">
  <div id="drawing-tools">
    <div class="st-brush-border">
      <button class='brush' id="super-tiny-brush"></button>
    </div>
    <div class="tiny-brush-border">
      <button class='brush active-brush' id="tiny-brush"></button>
    </div>
    <div class="small-brush-border">
      <button class='brush' id="small-brush"></button>
    </div>
    <div class="medium-brush-border">
      <button class='brush' id="medium-brush"></button>
    </div>
    <div class="large-brush-border">
      <button class='brush' id="large-brush"></button>
    </div>

    <button class="color" id="red"></button>
    <button class="color" id="orange"></button>
    <button class="color" id="yellow"></button>
    <button class="color" id="green"></button>
    <button class="color" id="blue"></button>
    <button class="color" id="purple"></button>
    <button class="color" id="brown"></button>
    <button class="color active-color" id="black"></button>
    <button class="color" id="gray"></button>
    <button class="color" id="white"></button>
    <p id='ink'><span>0</span> pixels</p>
    <button id="clear-canvas">Clear</button>
  </div>

  <div id="canvas-div" style='position:relative'>

    <div class='canvas-border'>
    <canvas width="600" height="600" id="canvas-partial-box"></canvas>
    <% if params[:parent_id] %>
    <form>
      <input type="hidden" id="parent-sketch-data" name="parent-sketch-data" value='<%= Sketch.find(params[:parent_id]).json_data %>'>
    </form>
    <% end %>
      </div>
  <div id='submit'>
      <button id="sketch-submit">Save this sketch</button>
  </div>
  </div>
</div>
</div>

app/views/sketches/_blank_canvas.html.erb
BIG TEST.
<canvas width="600" height="600" id="canvas"></canvas>

<%= form_for @sketch do |f| %>
  <%= f.submit %>
<% end %>

app/views/sketches/new.html.erb
  <%= javascript_tag do %>
    window.tree_id = <%= raw @tree.id.to_json %>
    window.parent_id = <%= raw params[:parent_id].to_json %>
  <% end %>
  <%= render "/shared/new_canvas" %>

app/views/sketches/show.html.erb
<button class="back-button"><%= link_to '← Tree View', tree_path(@tree.id) %></button>
<div class='static_picture'>
  <div class='parent_picture'>
    <h1>Parent</h1>
    <% if @sketch.parent != nil %>
    <a href='<%= tree_sketch_path(@sketch.tree_id, @sketch.parent.id) %>'>
      <canvas width="600" height="600" class="parent" id="sketch_parent"></canvas>
    </a>
    <p style='margin-top:0px'><%= link_to User.find(@sketch.parent.user_id).username, user_path(User.find(@sketch.parent.user_id).id) %></p>

    <script type="text/javascript">
      var jsonString = '<%= raw @sketch.parent.json_data %>';
      var sketchId = "sketch_parent";
      sketchCanvas = new fabric.StaticCanvas(sketchId, {isDrawingMode: false});
      sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
      $('.parent').css({'height': '300px', 'width': '300px', 'border': '1px solid black'})
    </script>
    <% end %>

  </div>

  <div class='sketch_picture'>
    <h1>Sketch</h1>
    <a href='<%= new_tree_sketch_path(parent_id: @sketch.id) %>'>
      <canvas width="600" height="600" class="sketch" id="sketch"></canvas>
    </a>
    <p style='margin-top:0px'><%= link_to User.find(@sketch.user_id).username, user_path(User.find(@sketch.user_id).id) %></p>
    <script type="text/javascript">
      var jsonString = '<%= raw @sketch.json_data %>';
      var sketchId = "sketch";
      sketchCanvas = new fabric.StaticCanvas(sketchId);
      sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
      $('.sketch').css({'height': '450px', 'width': '450px', 'border': '1px solid black'})
    </script>
    <p>Click this sketch to collaborate on it.</p>
  </div>
</div>

  <div class='children_picture_div'>
    <h1>Children</h1>

      <div class='children_picture'>
      <% @sketch.children.each_with_index do |children, index| %>
        <a href="<%= tree_sketch_path(children.tree_id, children.id) %>">
          <p style='margin-bottom:0px'><canvas width="600" height="600" class="children" id="sketch-<%= index %>"></canvas></p>
        </a>
      <p style='margin-top:0px'><%= link_to User.find(children.user_id).username, user_path(User.find(children.user_id).id) %></p>

        <script type="text/javascript">
          var jsonString = '<%= raw children.json_data %>';
          var sketchId = "sketch-" + "<%= index %>";
          sketchCanvas = new fabric.StaticCanvas(sketchId, {isDrawingMode: false});
          sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
          $('.children').css({'height': '200px', 'width': '200px', 'border': '1px solid black'})
        </script>
      <% end %>

        <a class='plus_a' href="<%= new_tree_sketch_path(parent_id: @sketch.id) %>">
          <div class='plus_box'>
            +
          </div>
        </a>
      </div>
    </div>
</div>

app/views/trees/index.html.erb
<div class="button-container">
<% sketch = Sketch.random %>

<h1 style='margin-bottom:0;'>Create and add to never-ending sketches.</h1>


  <form action='<%= new_tree_path %>'>
  <button style='margin-top:60px;' class="collab-button">Start Fresh</button>
<% if sketch %>
  </form>
    

      <button style='margin-top:60px' class="random-button" id="home-random-button">Randomize!</button>
    
<% end %>

</div>

<div id="index-container">

  <div class="two-column">
    <div class='popular'>
      <h2>Popular</h2>

      <h3>Click sketch to see its lineage.</h3>
      <% @popular_trees.each_with_index do |tree, index| %>
      <a href="<%= tree_path(tree.id) %>">
        <canvas width="600" height="600" class="tree-view-sketches" id="tree-<%= index %>"></canvas>
      </a>


      <% if tree.sketches.last != nil %>
      <script type="text/javascript">
      var jsonString = '<%= raw tree.sketches.last.json_data %>';
      var treeId = "tree-" + "<%= index %>";
      sketchCanvas = new fabric.StaticCanvas(treeId, {isDrawingMode: false});
      sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
      $('.tree-view-sketches').css({'border': '1px solid black', 'height': '400px', 'width': '400px'});
      </script>
      <% end %>
      <% end %>
    </div>

    <div class='recently-added'>
      <h2>Recent</h2>
      <h3>Add to a sketch</h3>
      <div class='recently-added-canvas'>
      <% @latest_sketches.each_with_index do |sketch, index| %>
      <a href="<%= new_tree_sketch_path(tree_id: sketch.tree.id ,parent_id: sketch.id) %>">
       <canvas width="600" height="600" class="most-recent-sketches" id="sketch-<%= index %>"></canvas>
     </a>
    <p style='margin-top:0px'><%= link_to User.find(sketch.user_id).username, user_path(User.find(sketch.user_id).id) %></p>

     <script type="text/javascript">
     var jsonString = '<%= raw sketch.json_data %>';
     var treeId = "sketch-" + "<%= index %>";
     sketchCanvas = new fabric.StaticCanvas(treeId, {isDrawingMode: false});
     sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
     $('.most-recent-sketches').css({'border': '1px solid black', 'height': '150px', 'width': '150px'});
     </script>
     <% end %>
   </div>
 </div>
</div>
</div>

app/views/trees/new.html.erb
<%= render "/shared/new_canvas" %>

app/views/trees/show.html.erb
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<%= javascript_tag do %>
  window.rootJSON = <%= raw @tree.build_tree %>
  window.sketches = <%= raw @sketches.to_json %>
  window.tID = <%= raw @tree.id %>
<% end %>

<h1>Explore sketch history</h1>

<div id='tree-json'>
</div>

app/views/users/new.html.erb
<div id="sign-up">
<h1>Sign Up</h1>
<div id="sign-form">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
  <% end %>

  <%= form_for(:user, url: users_path) do |f| %>
  <p><%= f.text_field :first_name, :placeholder => 'First Name' %></p>
  <p><%= f.text_field :last_name, :placeholder => 'Last Name' %></p>
  <p><%= f.text_field :username, :placeholder => 'Username' %></p>
  <p><%= f.text_field :email, :placeholder => 'Email' %></p>
  <p>
    <%= f.password_field :password, :placeholder => 'Password' %></br>
    <%= f.password_field :password_confirmation, :placeholder => 'Confirmation' %>
  </p>
  <%= f.submit 'Sign Up' %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="profile">
  <h1>Welcome to <%= @user.username %>'s profile page!</h1>
  <br>
  <h2> Below is a history of all <%= @user.username %>'s sketches </h2>
</nav>

<div class ='past_user_sketches'>
   <ul>
  <% @sketches.each_with_index do |sketch, index| %>
    <a href="<%= tree_sketch_path(sketch.tree_id, sketch.id) %>">
      <canvas width="600" height="600" class="sketch" id="sketch-<%= index %>"></canvas>
    </a>
    <script type="text/javascript">
      var jsonString = '<%= raw sketch.json_data %>';
      var sketchId = "sketch-" + "<%= index %>";
      sketchCanvas = new fabric.StaticCanvas(sketchId, {isDrawingMode: false});
      sketchCanvas.loadFromJSON(jsonString, sketchCanvas.renderAll.bind(sketchCanvas));
      $('.sketch').css({'height': '150px', 'width': '150px', 'border': '1px solid black'})
    </script>
  <% end %>
</div>
</div>